#include "data.h"
#include <string.h>

/* Symbols generated by objcopy from assets/input.bin.
   Path used: assets/input.bin -> symbols: _binary_assets_input_bin_start/_end */
extern const unsigned char _binary_assets_input_bin_start[];
extern const unsigned char _binary_assets_input_bin_end[];

const unsigned char* data_input_ptr(void) {
    return _binary_assets_input_bin_start;
}

size_t data_input_size(void) {
    return (size_t)(_binary_assets_input_bin_end - _binary_assets_input_bin_start);
}

int data_input_copy(size_t offset, size_t len, void *dst) {
    if (dst == NULL) return -1;
    size_t avail = data_input_size();
    if (offset >= avail) return 0;
    size_t max_copy = avail - offset;
    size_t to_copy = len < max_copy ? len : max_copy;
    memcpy(dst, (const void*)(_binary_assets_input_bin_start + offset), to_copy);
    return (int)to_copy;
}
